### ISSUE TITLE
Compilation fails. Not finding point_cloud_msg_wrapper

### ISSUE THREAD

**Issue by JLBicho** [smartmicro/smartmicro_ros2_radars#49]
Hello all,

First of all, thank you for working in this package. It was really needed.

Now for the issue, I'm currently working with Ubuntu 22.04 and ROS 2 Humble. I've downloaded this package and executed `./smart_extract.sh` and the output was correct.
I've installed `point_cloud_msg_wrapper` with `sudo apt install ros-humble-point-cloud-msg-wrapper` successfully. 

However, when I try to compile this package, I get the following error:
```
--- stderr: umrr_ros2_driver                                                                                                                     
/home/robotica/ws/sr001_ws/src/smartmicro_ros2_radars/umrr_ros2_driver/src/smartmicro_radar_node.cpp:19:10: fatal error: point_cloud_msg_wrapper/point_cloud_msg_wrapper.hpp: No such file or directory
   19 | #include <point_cloud_msg_wrapper/point_cloud_msg_wrapper.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/smartmicro_radar_node.dir/build.make:76: CMakeFiles/smartmicro_radar_node.dir/src/smartmicro_radar_node.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:155: CMakeFiles/smartmicro_radar_node.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< umrr_ros2_driver [0.70s, exited with code 2]
```

Is it possible that I'm missing something to install?

Thank you

**Comment by JLBicho** [comment]
Never mind, in my case it was enough to add the following to the `CMakeLists.txt`

L34: `find_package(point_cloud_msg_wrapper REQUIRED)`
L124: ```ament_target_dependencies(smartmicro_radar_node 
    point_cloud_msg_wrapper)```
